Made website Tor-friendly
hashcloak/hashcloak.github.io pull request #10
Opened 2022-05-26 18:18 UTC by sumi0820

# Freedcamp ticket URL
https://freedcamp.com/view/3202636/tasks/panel/task/46739751

# Description
- Added plane html and css for non-javascript browsers
- For the parts used JS such as the contact section, simply replaced it with a button to trigger an email client. 

https://dev-hashcloak.netlify.app/

## Type of change
UI update

# How Has This Been Tested?

- [x] Test A: Check browsers disabling JS
- [x] Test B: Check normal browsers to make sure the functions are working well.

2022-05-26 21:38 UTC, Mikerah requested changes

2022-05-26 21:38 UTC, Mikerah commented on src/components/templates/Supporters.tsx
> +  'We build vertically-intergrated privacy products for the cryptocurrency space.';
This should be removed as it's already in our product section

2022-05-27 14:43 UTC, sumi0820 commented on src/components/templates/Supporters.tsx
> +  'We build vertically-intergrated privacy products for the cryptocurrency space.';
I just removed the description, which is duplicated with the product section's one.

2022-05-27 16:55 UTC, Mikerah approved these changes

2022-05-27 17:53 UTC, merged